const $ = (id) => document.getElementById(id);
function show(el){ el.classList.remove("hidden"); }
function hide(el){ el.classList.add("hidden"); }
function openModal(backdrop){ backdrop.classList.add("show"); document.body.classList.add("noScroll"); }
function closeModal(backdrop){ backdrop.classList.remove("show"); document.body.classList.remove("noScroll"); }
function showErr(el,msg){ el.textContent=msg; el.classList.remove("hidden"); el.classList.remove("text-green-300"); el.classList.add("text-red-300"); }
function showOk(el,msg){ el.textContent=msg; el.classList.remove("hidden"); el.classList.remove("text-red-300"); el.classList.add("text-green-300"); }
function clearErr(el){ el.textContent=""; el.classList.add("hidden"); el.classList.remove("text-green-300"); el.classList.add("text-red-300"); }

let sb = window.__SB_CLIENT;
if (!sb){ sb = window.supabase.createClient(window.__SUPABASE_URL, window.__SUPABASE_ANON); window.__SB_CLIENT = sb; }

const COMPANY_SIZES = [
  { id:"s25", label:"Up to 25 People" },
  { id:"s100", label:"26 to 100 People" },
  { id:"s250", label:"101 to 250 People" },
  { id:"s250plus", label:"250+ People" }
];
const EXAMPLE_MODULES = ["Presence & Fire Safety","Policies & Staff Handbook","Holiday Booking","Accident & Injury Book","Training & Compliance","Onboarding & Offboarding","Expenses Upload","Wellbeing Check"];
const state = { size:null, custom:{what:"",why:"",who:"",flow:"",reports:"",integrations:"",other:""} };

const iconSVGs=[`<svg viewBox="0 0 24 24" fill="none"><path d="M12 3l8 4v6c0 5-3.5 8.5-8 8.5S4 18 4 13V7l8-4Z" stroke="white" stroke-opacity=".92" stroke-width="2"/></svg>`,`<svg viewBox="0 0 24 24" fill="none"><path d="M12 15a3 3 0 100-6 3 3 0 000 6Z" stroke="white" stroke-opacity=".92" stroke-width="2"/><path d="M19.4 15a8 8 0 10-14.8 0" stroke="white" stroke-opacity=".55" stroke-width="2"/></svg>`,`<svg viewBox="0 0 24 24" fill="none"><path d="M7 7h10v10H7V7Z" stroke="white" stroke-opacity=".92" stroke-width="2"/><path d="M4 10V4h6" stroke="white" stroke-opacity=".6" stroke-width="2"/><path d="M20 14v6h-6" stroke="white" stroke-opacity=".6" stroke-width="2"/></svg>`,`<svg viewBox="0 0 24 24" fill="none"><path d="M8 12h8" stroke="white" stroke-opacity=".92" stroke-width="2" stroke-linecap="round"/><path d="M12 8v8" stroke="white" stroke-opacity=".92" stroke-width="2" stroke-linecap="round"/></svg>`,`<svg viewBox="0 0 24 24" fill="none"><path d="M6 19h12M9 19V9l3-4 3 4v10" stroke="white" stroke-opacity=".85" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`];
const bubbles=[];
function buildBubbles(){ const f=$("iconField"); f.innerHTML=""; bubbles.length=0; const ok=window.matchMedia("(pointer:fine)").matches&&window.innerWidth>=900; if(!ok)return; [{x:12,y:18},{x:72,y:16},{x:86,y:48},{x:58,y:62},{x:18,y:60},{x:36,y:36},{x:84,y:78},{x:10,y:82}].forEach((p,i)=>{ const b=document.createElement("div"); b.className="bubble"; b.style.left=p.x+"%"; b.style.top=p.y+"%"; b.innerHTML=iconSVGs[i%iconSVGs.length]; b.style.setProperty("--tx","0px"); b.style.setProperty("--ty","0px"); f.appendChild(b); bubbles.push(b); }); }
function bubbleParallax(e){ if(!bubbles.length)return; const r=$("hero").getBoundingClientRect(); const cx=r.left+r.width/2; const cy=r.top+r.height/2; const dx=(e.clientX-cx)/r.width; const dy=(e.clientY-cy)/r.height; bubbles.forEach((b,i)=>{ const s=18+(i%3)*6; b.style.setProperty("--tx",(dx*s*-1).toFixed(1)+"px"); b.style.setProperty("--ty",(dy*s*-1).toFixed(1)+"px"); }); }
function initAnim(){ const io=new IntersectionObserver(es=>es.forEach(en=>{ if(en.isIntersecting) en.target.classList.add("in"); }),{threshold:.12}); document.querySelectorAll("[data-anim]").forEach(el=>{el.classList.add("fadeUp"); io.observe(el);}); }
function initNavHide(){ const nav=$("nav"); const io=new IntersectionObserver(es=>{ const en=es[0]; nav.classList.toggle("navShow", en.isIntersecting); nav.classList.toggle("navHide", !en.isIntersecting); },{threshold:.10}); io.observe($("hero")); }
function setCompanySize(sizeId){ state.size=COMPANY_SIZES.find(s=>s.id===sizeId)||null; document.querySelectorAll("[data-size]").forEach(btn=>btn.classList.toggle("selected",btn.dataset.size===sizeId)); if(state.size){ show($("modulesWrap")); if(state.size.id==="s250plus") show($("plusBox")); else { hide($("plusBox")); $("plusCount").value=""; $("plusNotes").value=""; hide($("plusWarn")); } setTimeout(()=>$("customBox").scrollIntoView({behavior:"smooth",block:"center"}),100); } else { hide($("modulesWrap")); hide($("plusBox")); } }
function renderExamples(){ const grid=$("examplesGrid"); grid.innerHTML=""; EXAMPLE_MODULES.forEach(name=>{ const card=document.createElement("div"); card.className="glass2 p-4 flex flex-col gap-2 commonChoice"; card.innerHTML=`<div class="font-semibold leading-tight">${name}</div><div class="text-xs opacity-60">Example SmartCore system</div>`; grid.appendChild(card); }); }
function buildPlanEmail(){ if(!state.size)return{error:"Select a company size first."}; let headcount=""; let notes=""; if(state.size.id==="s250plus"){ const approx=Number($("plusCount").value||0); if(!approx||approx<1){ showErr($("plusWarn"),"Please enter an approximate company size to continue."); return{error:"Missing 250+ headcount."}; } hide($("plusWarn")); headcount=`Approximate headcount: ${approx}`; notes=($("plusNotes").value||"").trim(); }
  const subject=`SmartCore Private Quote Request - ${state.size.label}`;
  const body=["Hello SmartCore Technology,","","We would like a private quote for a SmartCore system.","",`Company size band: ${state.size.label}`,headcount,notes?`Additional notes: ${notes}`:"","","Module details:",`What is it: ${state.custom.what || ""}`,`What's it for: ${state.custom.why || ""}`,`Who uses it: ${state.custom.who || ""}`,`Key workflow: ${state.custom.flow || ""}`,`Data / reporting needed: ${state.custom.reports || ""}`,`Integrations: ${state.custom.integrations || ""}`,`Anything else: ${state.custom.other || ""}`,"","Kind regards,","(Your name)","(Company name)","(Phone number)"].filter(Boolean).join("\n");
  return{mailto:`mailto:support@smartcoretechnology.co.uk?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}; }
async function login(){ clearErr($("liMsg")); $("liWrong").classList.add("hidden"); const email=$("liEmail").value.trim().toLowerCase(); const password=$("liPassword").value; if(!email)return showErr($("liMsg"),"Please enter your email."); if(!password)return showErr($("liMsg"),"Please enter your password."); $("liLogin").disabled=true; $("liLogin").classList.add("opacity-60"); try{ const {data,error}=await sb.auth.signInWithPassword({email,password}); if(error){$("liWrong").classList.remove("hidden"); throw new Error(error.message);} const uid=data?.user?.id; const {data:staff,error:staffErr}=await sb.from("smartcore_staff").select("id,user_id,email,role,active").or(`user_id.eq.${uid},email.eq.${email}`).eq("active",true).maybeSingle(); if(staffErr) throw new Error("Staff check failed: "+staffErr.message); if(!staff){ await sb.auth.signOut(); throw new Error("This login is for SmartCore personnel only."); } window.location.href="/hq"; }catch(e){ showErr($("liMsg"),String(e.message||"Login failed.")); }finally{ $("liLogin").disabled=false; $("liLogin").classList.remove("opacity-60"); } }
async function resetPassword(){ clearErr($("liMsg")); const email=$("liEmail").value.trim().toLowerCase(); if(!email)return showErr($("liMsg"),"Enter your email above, then click again."); try{ const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin}); if(error)throw new Error(error.message); showOk($("liMsg"),"Password reset email sent. Please check your inbox."); }catch(e){ showErr($("liMsg"),String(e.message||"Failed to send reset email.")); } }
function wire(){ $("heroBuild").onclick=()=>{ $("packages").scrollIntoView({behavior:"smooth",block:"start"}); if(!state.size) setTimeout(()=>setCompanySize("s25"),300); }; $("heroDown").onclick=()=>$("packages").scrollIntoView({behavior:"smooth",block:"start"}); $("navHome").onclick=()=>window.scrollTo({top:0,behavior:"smooth"}); $("navLogin").onclick=()=>openModal($("loginModalBackdrop")); document.querySelectorAll("[data-size]").forEach(btn=>btn.addEventListener("click",()=>setCompanySize(btn.dataset.size))); $("plusCount").addEventListener("input",()=>hide($("plusWarn"))); [["cWhat","what"],["cWhy","why"],["cWho","who"],["cFlow","flow"],["cReports","reports"],["cIntegrations","integrations"],["cOther","other"]].forEach(([id,key])=>$(id).addEventListener("input",()=>state.custom[key]=$(id).value.trim())); $("checkoutBtn").onclick=()=>{ const out=buildPlanEmail(); if(out.error){ alert(out.error==="Missing 250+ headcount."?"Please enter an approximate headcount.":out.error); return; } window.location.href=out.mailto; }; $("liClose").onclick=()=>closeModal($("loginModalBackdrop")); $("liEye").onclick=()=>{ const p=$("liPassword"); p.type=p.type==="password"?"text":"password"; $("liEye").textContent=p.type==="password"?"Show":"Hide"; }; $("liLogin").onclick=login; $("liReset").onclick=resetPassword; $("loginModalBackdrop").addEventListener("click",e=>{ if(e.target===$("loginModalBackdrop")) closeModal($("loginModalBackdrop")); }); window.addEventListener("mousemove",bubbleParallax,{passive:true}); window.addEventListener("resize",buildBubbles,{passive:true}); }
function init(){ buildBubbles(); initAnim(); initNavHide(); renderExamples(); wire(); }
init();
