export function cors(json, status=200){ return new Response(JSON.stringify(json),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,authorization'}}); }
export async function readJson(request){ return await request.json().catch(()=>({})); }
export function envRequired(env, key){ if(!env[key]) throw new Error(`Missing Cloudflare variable: ${key}`); return env[key]; }
export async function supabase(env){ const url=envRequired(env,'SUPABASE_URL'); const key=env.SUPABASE_SERVICE_ROLE || env.SUPABASE_SERVICE_ROLE_KEY; if(!key) throw new Error('Missing SUPABASE_SERVICE_ROLE or SUPABASE_SERVICE_ROLE_KEY'); return {url,key,headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json','prefer':'return=representation'}}; }
export async function db(env, path, options={}){ const s=await supabase(env); const r=await fetch(`${s.url}/rest/v1/${path}`,{...options,headers:{...s.headers,...(options.headers||{})}}); const text=await r.text(); let data; try{data=text?JSON.parse(text):null}catch{data=text} if(!r.ok) throw new Error(typeof data==='string'?data:(data.message||'Supabase request failed')); return data; }
export async function rpc(env, name, body){ return db(env,`rpc/${name}`,{method:'POST',body:JSON.stringify(body||{})}); }
export async function sha256(text){ const buf=await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)); return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
export function token(){ const a=new Uint8Array(32); crypto.getRandomValues(a); return [...a].map(b=>b.toString(16).padStart(2,'0')).join(''); }
export async function sendEmail(env,{to,subject,html}){ if(!env.RESEND_API_KEY) return {skipped:true}; const from=env.RESEND_FROM || env.RESEND_FROM_EMAIL || 'SmartCore Technology <noreply@smartcoretechnology.co.uk>'; const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from,to,subject,html})}); if(!r.ok) throw new Error('Email failed: '+await r.text()); return await r.json(); }
export function inviteEmail({title,body,link}){ return `<div style="font-family:Arial,sans-serif;background:#07111f;color:#eef6ff;padding:28px"><div style="max-width:620px;margin:auto;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.15);border-radius:18px;padding:24px"><h2>SmartCore Technology</h2><p style="color:#9fb2c8">Practical Technology. Built to Last.</p><h1>${title}</h1><p>${body}</p><p><a href="${link}" style="display:inline-block;background:#1f6feb;color:white;padding:12px 18px;border-radius:12px;text-decoration:none">Complete setup</a></p><p style="color:#9fb2c8;font-size:13px">Powered by SmartCore Technology</p></div></div>`; }
