name = "smartcore-holiday-management"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[triggers]
crons = ["0 8 * * *"]

[vars]
SUPABASE_URL = "https://hjdpcfhozhoyeqevnupm.supabase.co"
