
import { supabase, leaveSchema } from './supabase.js';
export const leaveTypeLabel=v=>v==='annual'?'Annual Leave':v==='sick'?'Sick Leave':'Other Leave';
export const dayTypeLabel=v=>v==='half_am'?'Half Day - Morning':v==='half_pm'?'Half Day - Afternoon':'Full Day';
export async function rpc(name,args={}){const {data,error}=await supabase.schema(leaveSchema).rpc(name,args); if(error)throw error; return data}
export async function table(name){return supabase.schema(leaveSchema).from(name)}
export async function getCompany(id){const {data,error}=await supabase.schema(leaveSchema).from('companies').select('*').eq('id',id).maybeSingle();if(error)throw error;return data}
export async function getEmployees(companyId){const {data,error}=await supabase.schema(leaveSchema).from('employees').select('*,shift_patterns(name)').eq('company_id',companyId).order('full_name');if(error)throw error;return data||[]}
export async function getEmployee(id){const {data,error}=await supabase.schema(leaveSchema).from('employees').select('*').eq('id',id).maybeSingle();if(error)throw error;return data}
export async function upsertEmployee(payload){const {data,error}=await supabase.schema(leaveSchema).rpc('upsert_employee',{payload});if(error){if(String(error.message).includes('MAX_EMPLOYEES_REACHED'))throw new Error('This company has reached its employee limit. Upgrade the plan before adding more active employees.');throw error}return data}
export async function sendEmployeeInvite(employee_id,email){return rpc('create_employee_invite',{p_employee_id:employee_id,p_email:email})}
export async function getShiftPatterns(companyId){const {data,error}=await supabase.schema(leaveSchema).from('shift_patterns').select('*').eq('company_id',companyId).order('name');if(error)throw error;return data||[]}
export async function createShiftPattern(payload){const {data,error}=await supabase.schema(leaveSchema).from('shift_patterns').insert([payload]).select().single();if(error)throw error;return data}
export async function getLeaveRequests(companyId){const {data,error}=await supabase.schema(leaveSchema).from('leave_requests').select('*,employees(full_name,job_title,department,work_email,personal_email,user_id,employee_code)').eq('company_id',companyId).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getMyLeave(profile){const {data,error}=await supabase.schema(leaveSchema).from('leave_requests').select('*').eq('employee_id',profile.employee_id).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getBalance(employeeId,year=new Date().getFullYear()){const {data,error}=await supabase.schema(leaveSchema).from('leave_balances').select('*').eq('employee_id',employeeId).eq('year',year).maybeSingle();if(error)throw error;return data}
export async function calculateLeaveDays(payload){return Number(await rpc('calculate_employee_leave_days',{p_employee_id:payload.employee_id,p_company_id:payload.company_id,p_start_date:payload.start_date,p_end_date:payload.end_date,p_leave_type:payload.leave_type,p_day_type:payload.day_type})||0)}
export async function createLeaveRequest(payload){const days=await calculateLeaveDays(payload); const {data,error}=await supabase.schema(leaveSchema).from('leave_requests').insert([{...payload,total_days:days,status:'pending',deduct_allowance:payload.leave_type!=='sick'}]).select().single();if(error)throw error;return data}
export async function approveRequest(request,approverId,note='',deduct=true){const days=await calculateLeaveDays({employee_id:request.employee_id,company_id:request.company_id,start_date:request.start_date,end_date:request.end_date,leave_type:request.leave_type,day_type:request.day_type});const {error}=await supabase.schema(leaveSchema).from('leave_requests').update({status:'approved',approved_by:approverId,approved_at:new Date().toISOString(),notes:note||request.notes,total_days:days,deduct_allowance:deduct}).eq('id',request.id);if(error)throw error;await rpc('sync_employee_balance',{p_employee_id:request.employee_id,p_year:new Date(request.start_date).getFullYear()})}
export async function rejectRequest(request,approverId,note=''){const {error}=await supabase.schema(leaveSchema).from('leave_requests').update({status:'rejected',approved_by:approverId,approved_at:new Date().toISOString(),notes:note||request.notes}).eq('id',request.id);if(error)throw error}
export async function cancelRequest(request,adminId,note=''){const {error}=await supabase.schema(leaveSchema).from('leave_requests').update({status:'cancelled',cancelled_by:adminId,cancelled_at:new Date().toISOString(),cancel_admin_reason:note}).eq('id',request.id);if(error)throw error;await rpc('sync_employee_balance',{p_employee_id:request.employee_id,p_year:new Date(request.start_date).getFullYear()})}
export async function requestCancellation(request,reason,userId){const {error}=await supabase.schema(leaveSchema).from('leave_requests').update({status:'cancel_requested',cancellation_reason:reason,cancellation_requested_by:userId,cancellation_requested_at:new Date().toISOString()}).eq('id',request.id);if(error)throw error}
export async function amendRequest(request,updates,adminId){const days=await calculateLeaveDays({employee_id:request.employee_id,company_id:request.company_id,start_date:updates.start_date,end_date:updates.end_date,leave_type:request.leave_type,day_type:updates.day_type});const {error}=await supabase.schema(leaveSchema).from('leave_requests').update({...updates,total_days:days,amended_by:adminId,amended_at:new Date().toISOString()}).eq('id',request.id);if(error)throw error;await rpc('sync_employee_balance',{p_employee_id:request.employee_id,p_year:new Date(updates.start_date).getFullYear()})}
export async function createManualAbsence(payload,adminId){if(!payload.employee?.user_id||payload.employee?.onboarding_status!=='complete')throw new Error('Manual leave can only be added once this employee has completed onboarding and has a linked login.');const days=await calculateLeaveDays({employee_id:payload.employee.id,company_id:payload.company_id,start_date:payload.start_date,end_date:payload.end_date,leave_type:payload.leave_type,day_type:payload.day_type});const {data,error}=await supabase.schema(leaveSchema).from('leave_requests').insert([{company_id:payload.company_id,employee_id:payload.employee.id,user_id:payload.employee.user_id,leave_type:payload.leave_type,day_type:payload.day_type,start_date:payload.start_date,end_date:payload.end_date,total_days:days,status:'approved',reason:payload.reason,notes:'Manually added by admin.',approved_by:adminId,approved_at:new Date().toISOString(),deduct_allowance:payload.deduct_allowance}]).select().single();if(error)throw error;await rpc('sync_employee_balance',{p_employee_id:payload.employee.id,p_year:new Date(payload.start_date).getFullYear()});return data}
export async function getApprovedLeaveForDate(companyId,date,department='all'){let q=supabase.schema(leaveSchema).from('leave_requests').select('*,employees(full_name,job_title,department)').eq('company_id',companyId).eq('status','approved').lte('start_date',date).gte('end_date',date);const {data,error}=await q;if(error)throw error;return (data||[]).filter(x=>department==='all'||x.employees?.department===department)}
export async function getLeaveOverlap(companyId,start,end,department='all'){const {data,error}=await supabase.schema(leaveSchema).from('leave_requests').select('*,employees(full_name,job_title,department)').eq('company_id',companyId).in('status',['approved','pending','cancel_requested']).lte('start_date',end).gte('end_date',start);if(error)throw error;return (data||[]).filter(x=>department==='all'||x.employees?.department===department)}
export async function getDepartments(companyId){const emps=await getEmployees(companyId);return [...new Set(emps.map(e=>e.department).filter(Boolean))].sort()}
export async function getHolidays(companyId){const {data,error}=await supabase.schema(leaveSchema).from('all_holidays').select('*').eq('company_id',companyId).order('holiday_date');if(error)throw error;return data||[]}
export async function addCompanyHoliday(payload){const {data,error}=await supabase.schema(leaveSchema).from('company_holidays').insert([payload]).select().single();if(error)throw error;return data}
export async function deleteCompanyHoliday(id){const {error}=await supabase.schema(leaveSchema).from('company_holidays').delete().eq('id',id);if(error)throw error}
export async function updateCompanyHoliday(id,payload){const {error}=await supabase.schema(leaveSchema).from('company_holidays').update(payload).eq('id',id);if(error)throw error}
export async function addCompany(payload){return rpc('smartcore_add_company',{payload})}
export async function getAllCompanies(){const {data,error}=await supabase.schema(leaveSchema).from('companies').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getOnboardingInvite(token){return rpc('get_invite_by_token',{p_token:token})}
export async function completeCompanyOnboarding(payload){return rpc('complete_company_onboarding',{payload})}
export async function completeEmployeeOnboarding(payload){return rpc('complete_employee_onboarding',{payload})}

export async function importBankHolidays(payload){
  const response = await fetch('/api/import-bank-holidays', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });
  const result = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(result.error || 'Could not import bank holidays.');
  return result;
}
