const SUPABASE_URL = 'https://hjdpcfhozhoyeqevnupm.supabase.co';
const SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqZHBjZmhvemhveWVxZXZudXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MTk3MzYsImV4cCI6MjA4MjQ5NTczNn0.BXosJO4NmEZOe73GXSGPa3z-i_4ZzF9zBAMBIf6Mkts';
const APP_BASE = '/systems/holidaymanagement';
const SCHEMA = 'holidaymanagement';
let sb = null;
let session = null;
let memberships = [];
let currentCompany = null;
let currentMembership = null;
let smartcoreAdmin = false;
let devRole = localStorage.getItem('smartcore_dev_role') || '';

const app = document.getElementById('app');
const toastEl = document.getElementById('toast');
const qs = new URLSearchParams(location.search);

function toast(msg){ toastEl.textContent = msg; toastEl.style.display='block'; setTimeout(()=>toastEl.style.display='none',3500); }
function esc(v){ return String(v ?? '').replace(/[&<>"]/g, s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s])); }
function fmt(d){ if(!d) return ''; return new Date(d+'T00:00:00').toLocaleDateString('en-GB'); }
function today(){ return new Date().toISOString().slice(0,10); }
function role(){ return devRole || currentMembership?.role || ''; }
function isAdmin(){ return smartcoreAdmin || ['owner','admin'].includes(role()); }
function isOwner(){ return role()==='owner' || smartcoreAdmin; }
function companyId(){ return currentCompany?.company_id || currentCompany?.id; }
function setRoute(name){ location.hash = name; render(); }
function h(html){ app.innerHTML = html; }
function api(path, body){ return fetch(`/api/${path}`, { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify(body||{}) }).then(async r=>{ const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j.error||'Request failed'); return j;}); }

async function init(){
  if(!SUPABASE_ANON){ h(`<div class="login"><div class="card"><h1>Missing Supabase anon key</h1><p>Add a plaintext Cloudflare variable called SUPABASE_ANON. Your URL is already set.</p></div></div>`); return; }
  sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON, { db:{schema:SCHEMA} });
  const {data} = await sb.auth.getSession(); session = data.session;
  sb.auth.onAuthStateChange((_e,s)=>{ session=s; boot(); });
  await boot();
}

async function boot(){
  const token = qs.get('token');
  if(token){ return renderOnboarding(token); }
  if(!session){ return renderLogin(); }
  await loadContext();
  if(smartcoreAdmin && location.hash==='#smartcore-admin') return renderShell('smartcore-admin');
  if(!currentCompany) return renderCompanySelector();
  render();
}

async function loadContext(){
  const {data: admin} = await sb.from('smartcore_admins').select('*').eq('user_id', session.user.id).eq('active',true).maybeSingle();
  smartcoreAdmin = !!admin;
  const {data,error} = await sb.rpc('get_my_memberships');
  memberships = error ? [] : data || [];
  const saved = localStorage.getItem('smartcore_company_id');
  currentCompany = memberships.find(m=>m.company_id===saved) || (memberships.length===1 ? memberships[0] : null);
  currentMembership = currentCompany;
}

function renderLogin(){
  h(`<div class="login"><div class="card"><div class="brand">SmartCore Technology</div><div class="tag">Practical Technology. Built to Last.</div><h1 style="margin-top:28px">Holiday Management</h1><p>Sign in to manage holiday requests, balances, employees and company holidays.</p><div class="grid"><label>Email<input id="email" type="email" autocomplete="email"></label><label>Password<input id="pass" type="password" autocomplete="current-password"></label><button class="btn primary" id="loginBtn">Sign in</button><button class="btn" id="resetBtn">Send password reset</button></div></div></div>`);
  document.getElementById('loginBtn').onclick = async()=>{ const email=emailVal('email'), password=emailVal('pass'); const {error}=await sb.auth.signInWithPassword({email,password}); if(error) toast(error.message); };
  document.getElementById('resetBtn').onclick = async()=>{ const email=emailVal('email'); if(!email) return toast('Enter your email first.'); const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+APP_BASE}); toast(error?error.message:'Password reset email sent.'); };
}
function emailVal(id){ return document.getElementById(id).value.trim(); }

function renderCompanySelector(){
  if(!memberships.length && !smartcoreAdmin) return h(`<div class="login"><div class="card"><h1>No companies linked</h1><p>This account is not linked to a company yet.</p><button class="btn" onclick="window.signOut()">Sign out</button></div></div>`);
  const adminCard = smartcoreAdmin ? `<div class="card"><h3>SmartCore Admin</h3><p>Manage customer companies and onboarding.</p><button class="btn primary" onclick="location.hash='smartcore-admin';window.renderShellPublic('smartcore-admin')">Open admin portal</button></div>`:'';
  h(`<div class="login"><div class="card" style="max-width:820px"><div class="brand">SmartCore Technology</div><h1>Select company</h1><p>Choose which company you want to work in.</p><div class="grid cols-2">${adminCard}${memberships.map(m=>`<div class="card"><h3>${esc(m.display_name||m.company_name)}</h3><p>${esc(m.role)}</p><button class="btn primary" onclick="window.enterCompany('${m.company_id}')">Enter</button></div>`).join('')}</div><p><button class="btn" onclick="window.signOut()">Sign out</button></p></div></div>`);
}
window.enterCompany=(id)=>{ localStorage.setItem('smartcore_company_id',id); currentCompany=memberships.find(m=>m.company_id===id); currentMembership=currentCompany; location.hash='dashboard'; render(); };
window.signOut=async()=>{ localStorage.removeItem('smartcore_company_id'); await sb.auth.signOut(); };
window.renderShellPublic=renderShell;

function render(){ const route=(location.hash||'#dashboard').slice(1); renderShell(route); }
window.addEventListener('hashchange',()=>{ if(session) render(); });
function navItem(id,label,admin=false){ if(admin&&!isAdmin())return''; return `<button class="${(location.hash||'#dashboard')==='#'+id?'active':''}" onclick="location.hash='${id}'">${label}</button>`; }
function renderShell(route){
  h(`<div class="shell"><aside class="sidebar"><div class="brand">SmartCore Technology</div><div class="tag">Practical Technology. Built to Last.</div><div style="margin-top:18px" class="badge">${esc(currentCompany?.display_name||currentCompany?.company_name||'Admin')}</div><nav class="nav">${smartcoreAdmin?navItem('smartcore-admin','SmartCore Admin'):''}${currentCompany?navItem('dashboard','Dashboard'):''}${currentCompany?navItem('calendar','Calendar'):''}${currentCompany?navItem('request','Request Leave'):''}${currentCompany?navItem('my-leave','My Leave'):''}${currentCompany?navItem('admin','Admin Panel',true):''}${currentCompany?navItem('employees','Employees',true):''}${currentCompany?navItem('holidays','Company Holidays',true):''}${currentCompany?navItem('settings','Settings',true):''}<button onclick="window.switchCompany()">Switch Company</button><button onclick="window.signOut()">Sign out</button></nav></aside><main class="main"><div id="devbar" class="devbar ${smartcoreAdmin?'show':''}"><strong>Developer mode</strong><select id="devRole"><option value="">Actual role</option><option value="owner">Owner</option><option value="admin">Admin</option><option value="employee">Employee</option></select><button class="btn" id="devApply">Apply</button><span class="muted">SmartCore admins only</span></div><div id="page"></div></main></div>`);
  if(smartcoreAdmin){ document.getElementById('devRole').value=devRole; document.getElementById('devApply').onclick=()=>{devRole=document.getElementById('devRole').value;localStorage.setItem('smartcore_dev_role',devRole);render();}; }
  const page=document.getElementById('page');
  ({'dashboard':dashboard,'calendar':calendar,'request':requestLeave,'my-leave':myLeave,'admin':adminPanel,'employees':employees,'holidays':holidays,'settings':settings,'smartcore-admin':smartcoreAdminPage}[route]||dashboard)(page);
}
window.switchCompany=()=>{ localStorage.removeItem('smartcore_company_id'); currentCompany=null; renderCompanySelector(); };

async function dashboard(page){
  page.innerHTML=`<div class="topbar"><div><h1>Holiday Management</h1><p>${esc(currentCompany?.display_name||'')} overview</p></div><button class="btn primary" onclick="location.hash='request'">Request leave</button></div><div class="grid cols-4" id="stats"></div><div class="grid cols-2" style="margin-top:16px"><div class="card"><h2>Pending requests</h2><div id="pending"></div></div><div class="card"><h2>People off today</h2><div id="offToday"></div></div></div>`;
  const cid=companyId();
  const [{data:reqs},{data:emps},{data:todayOff}] = await Promise.all([
    sb.from('leave_requests').select('*,employees(full_name,job_title)').eq('company_id',cid).order('created_at',{ascending:false}).limit(10),
    sb.from('employees').select('*').eq('company_id',cid).eq('employment_status','active'),
    sb.from('leave_requests').select('*,employees(full_name,job_title)').eq('company_id',cid).lte('start_date',today()).gte('end_date',today()).eq('status','approved')
  ]);
  const pending=(reqs||[]).filter(r=>r.status==='pending');
  document.getElementById('stats').innerHTML=[['Employees',(emps||[]).length],['Pending',pending.length],['Off today',(todayOff||[]).length],['Your role',role()]].map(s=>`<div class="card"><div class="muted">${s[0]}</div><div class="stat">${s[1]}</div></div>`).join('');
  document.getElementById('pending').innerHTML=pending.length?pending.map(requestCard).join(''):'<p>No pending requests.</p>';
  document.getElementById('offToday').innerHTML=(todayOff||[]).length?todayOff.map(r=>`<p><strong>${esc(r.employees?.full_name)}</strong><br><span class="muted">${esc(r.employees?.job_title)}</span></p>`).join(''):'<p>No one is off today.</p>';
}
function requestCard(r){ return `<div class="card" style="margin:10px 0"><strong>${esc(r.employees?.full_name||'Employee')}</strong><p>${esc(r.leave_type)} ${fmt(r.start_date)} to ${fmt(r.end_date)} • ${r.total_days} days</p><span class="badge ${r.status==='approved'?'good':r.status==='pending'?'warn':'bad'}">${esc(r.status)}</span></div>`; }

async function requestLeave(page){
  const cid=companyId();
  const {data: meEmp}=await sb.from('employees').select('*').eq('company_id',cid).eq('user_id',session.user.id).maybeSingle();
  page.innerHTML=`<div class="topbar"><div><h1>Request Leave</h1><p>Submit a holiday request to your authoriser.</p></div></div><div class="card"><div class="form-grid"><label>Leave type<select id="leave_type"><option value="annual">Annual Leave</option>${isAdmin()?'<option value="sick">Sick Leave</option><option value="other">Other Leave</option><option value="unpaid">Unpaid Leave</option>':''}</select></label><label>Day type<select id="day_type"><option value="full">Full day / multiple days</option><option value="half_morning">Half day morning</option><option value="half_afternoon">Half day afternoon</option></select></label><label>Start date<input id="start_date" type="date"></label><label>End date<input id="end_date" type="date"></label><label>Total days<input id="total_days" readonly></label><label>Reason<textarea id="reason"></textarea></label><label>Notes<textarea id="notes"></textarea></label></div><div class="actions" style="margin-top:16px"><button class="btn" id="calcBtn">Calculate</button><button class="btn primary" id="submitBtn">Submit request</button></div></div>`;
  ['start_date','end_date','day_type'].forEach(id=>document.getElementById(id).onchange=()=>calculateTotal(meEmp));
  document.getElementById('calcBtn').onclick=()=>calculateTotal(meEmp);
  document.getElementById('submitBtn').onclick=async()=>{
    if(!meEmp) return toast('Your employee profile is not linked yet.');
    await calculateTotal(meEmp);
    const row={company_id:cid,user_id:session.user.id,employee_id:meEmp.id,leave_type:val('leave_type'),day_type:val('day_type'),start_date:val('start_date'),end_date:val('end_date'),total_days:Number(val('total_days')||0),reason:val('reason'),notes:val('notes'),deduct_allowance:val('leave_type')==='annual'};
    const {error}=await sb.from('leave_requests').insert(row); if(error) return toast(error.message); toast('Leave request submitted.'); location.hash='my-leave';
  };
}
function val(id){return document.getElementById(id).value;}
async function calculateTotal(emp){
  const s=val('start_date'), e=val('end_date')||s, dayType=val('day_type'); if(!s){return 0}
  if(dayType!=='full'){ document.getElementById('end_date').value=s; document.getElementById('total_days').value='0.5'; return .5; }
  let count=0; let d=new Date(s+'T00:00:00'), end=new Date(e+'T00:00:00');
  const pat=emp?.shift_pattern_id ? (await sb.from('shift_patterns').select('*').eq('id',emp.shift_pattern_id).maybeSingle()).data : null;
  const workDays=pat?['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].map(x=>!!pat[x]):[false,true,true,true,true,true,false];
  while(d<=end){ if(workDays[d.getDay()]) count++; d.setDate(d.getDate()+1); }
  document.getElementById('total_days').value=count; return count;
}

async function myLeave(page){
  const cid=companyId();
  const {data: emp}=await sb.from('employees').select('*').eq('company_id',cid).eq('user_id',session.user.id).maybeSingle();
  if(!emp){ page.innerHTML='<div class="card"><h1>My Leave</h1><p>Your employee record is not linked yet.</p></div>'; return; }
  const year=new Date().getFullYear();
  const [{data:bal},{data:reqs}]=await Promise.all([sb.from('leave_balances').select('*').eq('employee_id',emp.id).eq('year',year).maybeSingle(),sb.from('leave_requests').select('*').eq('employee_id',emp.id).order('created_at',{ascending:false})]);
  page.innerHTML=`<div class="topbar"><div><h1>My Leave</h1><p>Welcome, ${esc(emp.full_name)}.</p></div><button class="btn primary" onclick="location.hash='request'">Request leave</button></div><div class="grid cols-4"><div class="card"><div class="muted">Allowance</div><div class="stat">${bal?.total_allowance ?? emp.annual_leave_allowance}</div></div><div class="card"><div class="muted">Used</div><div class="stat">${bal?.used_days ?? 0}</div></div><div class="card"><div class="muted">Remaining</div><div class="stat">${bal?.remaining_days ?? emp.annual_leave_allowance}</div></div><div class="card"><div class="muted">Pending</div><div class="stat">${bal?.pending_days ?? 0}</div></div></div><div class="card" style="margin-top:16px"><h2>Leave history</h2>${(reqs||[]).map(r=>`<div class="card" style="margin:10px 0"><strong>${esc(r.leave_type)}</strong><p>${fmt(r.start_date)} to ${fmt(r.end_date)} • ${r.total_days} days • ${esc(r.day_type)}</p><p>${esc(r.reason||'')}</p><span class="badge">${esc(r.status)}</span>${r.status==='approved'?` <button class="btn" onclick="window.requestCancel('${r.id}')">Request cancellation</button>`:''}</div>`).join('')||'<p>No leave records yet.</p>'}</div>`;
}
window.requestCancel=async(id)=>{ const reason=prompt('Reason for cancellation?')||''; const {error}=await sb.from('leave_requests').update({status:'cancellation_requested',cancellation_requested_at:new Date().toISOString(),cancellation_requested_by:session.user.id,cancellation_reason:reason}).eq('id',id); toast(error?error.message:'Cancellation requested.'); render(); };

async function adminPanel(page){ if(!isAdmin()) return page.innerHTML='<div class="card"><h1>No access</h1></div>'; const cid=companyId();
  const {data:reqs}=await sb.from('leave_requests').select('*,employees(full_name,job_title,user_id,onboarding_status)').eq('company_id',cid).order('created_at',{ascending:false});
  page.innerHTML=`<div class="topbar"><div><h1>Admin Panel</h1><p>Approve, reject, amend and manage leave.</p></div><button class="btn primary" onclick="window.openManualAbsence()">Add manual absence</button></div><div class="card"><table class="table"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Status</th><th>Actions</th></tr></thead><tbody>${(reqs||[]).map(r=>`<tr><td>${esc(r.employees?.full_name)}<br><span class="muted">${esc(r.employees?.job_title)}</span></td><td>${esc(r.leave_type)}<br>${esc(r.day_type)}</td><td>${fmt(r.start_date)} to ${fmt(r.end_date)}<br>${r.total_days} days</td><td><span class="badge">${esc(r.status)}</span></td><td class="actions"><button class="btn good" onclick="window.approveLeave('${r.id}','${r.user_id||''}')">Approve</button><button class="btn danger" onclick="window.rejectLeave('${r.id}')">Reject</button><button class="btn" onclick="window.moreInfo('${r.id}')">More info</button></td></tr>`).join('')}</tbody></table></div><div id="modal" class="modal"><div class="modal-box card" id="modalBox"></div></div>`;
}
window.approveLeave=async(id,userId)=>{ if(userId===session.user.id&&!isOwner()) return toast('Admins cannot approve their own leave.'); const {error}=await sb.from('leave_requests').update({status:'approved',approved_by:session.user.id,approved_at:new Date().toISOString()}).eq('id',id); toast(error?error.message:'Approved.'); render(); };
window.rejectLeave=async(id)=>{ const {error}=await sb.from('leave_requests').update({status:'rejected',rejected_by:session.user.id,rejected_at:new Date().toISOString()}).eq('id',id); toast(error?error.message:'Rejected.'); render(); };
window.moreInfo=async(id)=>{ const {data:r}=await sb.from('leave_requests').select('*,employees(*)').eq('id',id).single(); modal(`<h2>Request details</h2>${requestCard(r)}<p><strong>Reason:</strong> ${esc(r.reason)}</p><p><strong>Notes:</strong> ${esc(r.notes)}</p><button class="btn" onclick="window.closeModal()">Close</button>`); };
window.openManualAbsence=async()=>{ const {data:emps}=await sb.from('employees').select('*').eq('company_id',companyId()).eq('employment_status','active').order('full_name'); modal(`<h2>Manual absence</h2><div class="form-grid"><label>Employee<select id="m_emp">${(emps||[]).map(e=>`<option value="${e.id}" data-user="${e.user_id||''}" data-onboard="${e.onboarding_status}">${esc(e.full_name)}</option>`).join('')}</select></label><label>Type<select id="m_type"><option value="annual">Annual</option><option value="sick">Sick</option><option value="other">Other</option></select></label><label>Day type<select id="m_day"><option value="full">Full</option><option value="half_morning">Half morning</option><option value="half_afternoon">Half afternoon</option></select></label><label>Start<input id="m_start" type="date"></label><label>End<input id="m_end" type="date"></label><label>Reason<textarea id="m_reason"></textarea></label></div><div class="actions"><button class="btn primary" onclick="window.saveManual()">Save absence</button><button class="btn" onclick="window.closeModal()">Cancel</button></div>`); };
window.saveManual=async()=>{ const sel=document.getElementById('m_emp').selectedOptions[0]; if(!sel.dataset.user || sel.dataset.onboard!=='complete') return toast('Manual leave can only be added once this employee has completed onboarding.'); const row={company_id:companyId(),employee_id:val('m_emp'),user_id:sel.dataset.user,leave_type:val('m_type'),day_type:val('m_day'),start_date:val('m_start'),end_date:val('m_day')==='full'?val('m_end'):val('m_start'),total_days:val('m_day')==='full'?1:.5,status:'approved',reason:val('m_reason'),deduct_allowance:val('m_type')==='annual',approved_by:session.user.id,approved_at:new Date().toISOString()}; const {error}=await sb.from('leave_requests').insert(row); toast(error?error.message:'Manual absence saved.'); if(!error){closeModal(); render();} };
function modal(html){ document.getElementById('modal').classList.add('open'); document.getElementById('modalBox').innerHTML=html; }
window.closeModal=()=>document.getElementById('modal').classList.remove('open');

async function employees(page){ if(!isAdmin()) return page.innerHTML='<div class="card"><h1>No access</h1></div>'; const cid=companyId(); const [{data:emps},{data:company},{data:patterns}]=await Promise.all([sb.from('employees').select('*,shift_patterns(name)').eq('company_id',cid).order('full_name'),sb.from('companies').select('*').eq('id',cid).single(),sb.from('shift_patterns').select('*').eq('company_id',cid)]);
 const active=(emps||[]).filter(e=>e.employment_status==='active').length;
 page.innerHTML=`<div class="topbar"><div><h1>Employees</h1><p>${active} of ${company?.max_employees||0} active employee spaces used.</p></div><button class="btn primary" onclick="window.employeeForm()">Add employee</button></div><div class="card"><table class="table"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Onboarding</th><th>Actions</th></tr></thead><tbody>${(emps||[]).map(e=>`<tr><td><strong>${esc(e.full_name)}</strong><br>${esc(e.employee_code)}<br><span class="muted">${esc(e.work_email)}</span></td><td>${esc(e.job_title)}<br><span class="badge">${esc(e.role)}</span></td><td>${esc(e.employment_status)}</td><td>${esc(e.onboarding_status)}<br>${e.first_login_at?new Date(e.first_login_at).toLocaleString('en-GB'):'No first login'}</td><td class="actions"><button class="btn" onclick="window.viewEmployee('${e.id}')">View</button><button class="btn" onclick="window.employeeForm('${e.id}')">Edit</button><button class="btn" onclick="window.sendInvite('${e.id}')">Send invite</button></td></tr>`).join('')}</tbody></table></div><div id="modal" class="modal"><div class="modal-box card" id="modalBox"></div></div>`;
 window._emps=emps||[]; window._patterns=patterns||[]; window._company=company; };
window.employeeForm=async(id)=>{ const e=id?window._emps.find(x=>x.id===id):{}; const add=!id; const patterns=window._patterns||[]; modal(`<h2>${add?'Add employee':'Edit employee'}</h2><p>${add?'Only work details are required now. Personal details are completed by the employee during onboarding.':'Full employee profile.'}</p><div class="form-grid"><label>Full name<input id="e_full" value="${esc(e.full_name)}"></label><label>Job title<input id="e_job" value="${esc(e.job_title)}"></label><label>Work email<input id="e_work" value="${esc(e.work_email)}"></label><label>Personal email<input id="e_personal" value="${esc(e.personal_email)}"></label><label>Personal phone<input id="e_phone" value="${esc(e.personal_phone)}"></label><label>Employment type<input id="e_type" value="${esc(e.employment_type)}"></label><label>Notice period<input id="e_notice" value="${esc(e.notice_period)}"></label><label>Role<select id="e_role"><option>employee</option><option>admin</option><option>owner</option></select></label><label>Status<select id="e_status"><option>active</option><option>pending</option><option>archived</option><option>leaver</option></select></label><label>Annual allowance<input id="e_allow" type="number" step="0.5" value="${e.annual_leave_allowance||window._company?.default_annual_leave_allowance||28}"></label><label>Start date<input id="e_start" type="date" value="${esc(e.start_date)}"></label><label>Shift pattern<select id="e_shift"><option value="">Default</option>${patterns.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label><span><input id="e_override_on" type="checkbox" ${e.override_allowance_calculation?'checked':''}> Use Executive Allowance Override for this year</span><input id="e_override" type="number" step="0.5" value="${e.override_allowance_this_year??''}"></label>${!add?`<label>Address line 1<input id="e_addr1" value="${esc(e.address_line_1)}"></label><label>Postcode<input id="e_post" value="${esc(e.postcode)}"></label><label>Emergency contact 1<input id="e_ec1" value="${esc(e.emergency_contact_1_name)}"></label><label>Emergency phone 1<input id="e_ecp1" value="${esc(e.emergency_contact_1_phone)}"></label>`:''}</div><div class="actions" style="margin-top:16px"><button class="btn" onclick="window.closeModal()">Cancel</button><button class="btn primary" onclick="window.saveEmployee('${id||''}')">Save Employee</button>${!add?'<button class="btn danger" onclick="window.archiveEmployee(\''+id+'\')">Archive</button>':''}</div>`); if(e.role)document.getElementById('e_role').value=e.role; if(e.employment_status)document.getElementById('e_status').value=e.employment_status; if(e.shift_pattern_id)document.getElementById('e_shift').value=e.shift_pattern_id; };
window.saveEmployee=async(id)=>{ const cid=companyId(); if(!id){ const active=window._emps.filter(e=>e.employment_status==='active').length; if(active >= window._company.max_employees) return toast(`This company has reached its employee limit of ${window._company.max_employees}.`); }
 const row={company_id:cid,full_name:val('e_full'),job_title:val('e_job'),work_email:val('e_work'),personal_email:val('e_personal'),personal_phone:val('e_phone'),employment_type:val('e_type'),notice_period:val('e_notice'),role:val('e_role'),is_admin:['owner','admin'].includes(val('e_role')),employment_status:val('e_status'),annual_leave_allowance:Number(val('e_allow')||0),start_date:val('e_start')||null,shift_pattern_id:val('e_shift')||null,override_allowance_calculation:document.getElementById('e_override_on').checked,override_allowance_this_year:document.getElementById('e_override_on').checked?Number(val('e_override')||0):null}; if(!id){ row.onboarding_status='pending'; } const q=id?sb.from('employees').update(row).eq('id',id):sb.from('employees').insert(row); const {data,error}=await q.select().single(); toast(error?error.message:'Employee saved.'); if(!error){ closeModal(); if(!id && confirm('Send onboarding invite now?')) await window.sendInvite(data.id); render(); } };
window.sendInvite=async(id)=>{ try{ const res=await api('send-employee-invite',{employee_id:id}); toast('Invite sent.'); }catch(e){ toast(e.message); } };
window.archiveEmployee=async(id)=>{ const {error}=await sb.from('employees').update({employment_status:'archived'}).eq('id',id); toast(error?error.message:'Employee archived.'); closeModal(); render(); };
window.viewEmployee=async(id)=>{ const {data:e}=await sb.from('employees').select('*').eq('id',id).single(); const {data:reqs}=await sb.from('leave_requests').select('*').eq('employee_id',id).order('start_date',{ascending:false}); modal(`<h2>${esc(e.full_name)}</h2><p>${esc(e.job_title)} • ${esc(e.employee_code)}</p><div class="grid cols-3"><div class="card"><strong>Work email</strong><p>${esc(e.work_email)}</p></div><div class="card"><strong>First login</strong><p>${e.first_login_at?new Date(e.first_login_at).toLocaleString('en-GB'):'Not yet'}</p></div><div class="card"><strong>Allowance</strong><p>${e.annual_leave_allowance}</p></div></div><h3>Leave records</h3>${(reqs||[]).map(requestCard).join('')||'<p>No records.</p>'}<button class="btn" onclick="window.closeModal()">Close</button>`); };

async function calendar(page){ const cid=companyId(); const now=new Date(); const ym=qs.get('m')||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`; const [y,m]=ym.split('-').map(Number); const first=new Date(y,m-1,1); const last=new Date(y,m,0); const {data:reqs}=await sb.from('leave_requests').select('*,employees(full_name,job_title)').eq('company_id',cid).eq('status','approved').lte('start_date',last.toISOString().slice(0,10)).gte('end_date',first.toISOString().slice(0,10)); const days=[]; for(let i=1;i<=last.getDate();i++){ const d=`${y}-${String(m).padStart(2,'0')}-${String(i).padStart(2,'0')}`; const off=(reqs||[]).filter(r=>r.start_date<=d&&r.end_date>=d); days.push(`<div class="day" onclick="window.showDay('${d}')"><strong>${i}</strong><br>${off.map(()=>'<span class="dot"></span>').join('')}</div>`); } page.innerHTML=`<div class="topbar"><div><h1>${first.toLocaleString('en-GB',{month:'long',year:'numeric'})}</h1><p>Click a date to see who is off.</p></div><div class="actions"><button class="btn" onclick="window.changeMonth(-1)">Previous</button><button class="btn" onclick="window.changeMonth(1)">Next</button></div></div><div class="card"><div class="calendar">${days.join('')}</div></div><div id="modal" class="modal"><div class="modal-box card" id="modalBox"></div></div>`; window._calReqs=reqs||[]; window._calY=y; window._calM=m; }
window.changeMonth=(delta)=>{ let d=new Date(window._calY,window._calM-1+delta,1); location.search='?m='+d.toISOString().slice(0,7); };
window.showDay=(d)=>{ const off=window._calReqs.filter(r=>r.start_date<=d&&r.end_date>=d); modal(`<h2>${fmt(d)}</h2>${off.map(r=>`<p><strong>${esc(r.employees?.full_name)}</strong><br><span class="muted">${esc(r.employees?.job_title)}</span></p>`).join('')||'<p>No one is off.</p>'}<button class="btn" onclick="window.closeModal()">Close</button>`); };

async function holidays(page){ if(!isAdmin()) return page.innerHTML='<div class="card"><h1>No access</h1></div>'; const {data:hs}=await sb.from('company_holidays').select('*').eq('company_id',companyId()).order('holiday_date'); page.innerHTML=`<div class="topbar"><div><h1>Company Holidays</h1><p>Manage shutdown days and company holidays.</p></div></div><div class="card"><div class="form-grid"><label>Name<input id="h_name"></label><label>Date<input id="h_date" type="date"></label></div><button class="btn primary" style="margin-top:12px" onclick="window.addHoliday()">Add holiday</button></div><div class="card" style="margin-top:16px"><table class="table"><tbody>${(hs||[]).map(x=>`<tr><td>${fmt(x.holiday_date)}</td><td>${esc(x.name)}</td><td><button class="btn danger" onclick="window.deleteHoliday('${x.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`; }
window.addHoliday=async()=>{ const {error}=await sb.from('company_holidays').insert({company_id:companyId(),name:val('h_name'),holiday_date:val('h_date'),type:'company'}); toast(error?error.message:'Holiday added.'); render(); };
window.deleteHoliday=async(id)=>{ const {error}=await sb.from('company_holidays').delete().eq('id',id); toast(error?error.message:'Deleted.'); render(); };

async function settings(page){ if(!isAdmin()) return page.innerHTML='<div class="card"><h1>No access</h1></div>'; const [{data:c},{data:patterns}]=await Promise.all([sb.from('companies').select('*').eq('id',companyId()).single(),sb.from('shift_patterns').select('*').eq('company_id',companyId())]); page.innerHTML=`<div class="topbar"><div><h1>Company Settings</h1><p>Holiday year, bank holidays, allowances and employee limit.</p></div></div><div class="card"><div class="form-grid"><label>Display name<input id="s_display" value="${esc(c.display_name||'')}"></label><label>Max employees<input id="s_max" type="number" value="${c.max_employees}"></label><label>Holiday year start month<input id="s_month" type="number" min="1" max="12" value="${c.holiday_year_start_month}"></label><label>Holiday year start day<input id="s_day" type="number" min="1" max="31" value="${c.holiday_year_start_day}"></label><label>Bank holiday region<select id="s_region"><option value="england-and-wales">England and Wales</option><option value="scotland">Scotland</option><option value="northern-ireland">Northern Ireland</option></select></label><label>Default annual allowance<input id="s_allow" type="number" step="0.5" value="${c.default_annual_leave_allowance}"></label><label><span><input id="s_bh" type="checkbox" ${c.bank_holidays_included_in_allowance?'checked':''}> Bank holidays included in allowance</span></label></div><button class="btn primary" style="margin-top:14px" onclick="window.saveSettings()">Save settings</button></div><div class="card" style="margin-top:16px"><h2>Shift patterns</h2><p>Create patterns in SQL for now or extend this screen later. Current patterns: ${(patterns||[]).map(p=>esc(p.name)).join(', ')||'None'}</p></div>`; document.getElementById('s_region').value=c.default_bank_holiday_region; }
window.saveSettings=async()=>{ const row={display_name:val('s_display'),max_employees:Number(val('s_max')),holiday_year_start_month:Number(val('s_month')),holiday_year_start_day:Number(val('s_day')),default_bank_holiday_region:val('s_region'),default_annual_leave_allowance:Number(val('s_allow')),bank_holidays_included_in_allowance:document.getElementById('s_bh').checked}; const {error}=await sb.from('companies').update(row).eq('id',companyId()); toast(error?error.message:'Settings saved.'); };

async function smartcoreAdminPage(page){ if(!smartcoreAdmin) return page.innerHTML='<div class="card"><h1>No access</h1></div>'; const {data:companies}=await sb.from('companies').select('*').order('created_at',{ascending:false}); page.innerHTML=`<div class="topbar"><div><h1>SmartCore Admin</h1><p>Add and manage customer companies.</p></div><button class="btn primary" onclick="window.addCompanyModal()">Add Company</button></div><div class="card"><table class="table"><thead><tr><th>Company</th><th>Owner</th><th>Status</th><th>Max employees</th><th>Actions</th></tr></thead><tbody>${(companies||[]).map(c=>`<tr><td><strong>${esc(c.display_name||c.company_name)}</strong><br><span class="muted">${new Date(c.created_at).toLocaleDateString('en-GB')}</span></td><td>${esc(c.owner_name)}<br>${esc(c.owner_email)}</td><td><span class="badge">${esc(c.status)}</span></td><td>${c.max_employees}</td><td class="actions"><button class="btn" onclick="window.resendOwner('${c.id}')">Resend onboarding</button><button class="btn" onclick="window.enterSupportCompany('${c.id}')">Support view</button></td></tr>`).join('')}</tbody></table></div><div id="modal" class="modal"><div class="modal-box card" id="modalBox"></div></div>`; window._adminCompanies=companies||[]; }
window.addCompanyModal=()=>modal(`<h2>Add Company</h2><div class="form-grid"><label>Company name<input id="ac_name"></label><label>Owner full name<input id="ac_owner"></label><label>Owner email<input id="ac_email" type="email"></label><label>Owner phone<input id="ac_phone"></label><label>Max employees<input id="ac_max" type="number" value="25"></label><label>Initial plan/package<input id="ac_plan"></label><label>Notes<textarea id="ac_notes"></textarea></label></div><div class="actions"><button class="btn primary" onclick="window.createCompany()">Create and send invite</button><button class="btn" onclick="window.closeModal()">Cancel</button></div>`);
window.createCompany=async()=>{ try{ await api('create-company',{company_name:val('ac_name'),owner_name:val('ac_owner'),owner_email:val('ac_email'),owner_phone:val('ac_phone'),max_employees:Number(val('ac_max')||25),plan_name:val('ac_plan'),notes:val('ac_notes'),actor_user_id:session.user.id}); toast('Company created and invite sent.'); closeModal(); smartcoreAdminPage(document.getElementById('page')); }catch(e){ toast(e.message); } };
window.resendOwner=async(id)=>{ try{ await api('resend-owner-invite',{company_id:id}); toast('Owner invite resent.'); }catch(e){toast(e.message);} };
window.enterSupportCompany=(id)=>{ const c=window._adminCompanies.find(x=>x.id===id); currentCompany={company_id:id,company_name:c.company_name,display_name:c.display_name,role:'owner'}; currentMembership=currentCompany; localStorage.setItem('smartcore_company_id',id); location.hash='dashboard'; render(); };

async function renderOnboarding(token){
  h(`<div class="login"><div class="card"><h1>Complete setup</h1><p>Checking your secure link...</p></div></div>`);
  let data; try{ data=await api('check-invite',{token}); }catch(e){ h(`<div class="login"><div class="card"><h1>Link problem</h1><p>${esc(e.message)}</p></div></div>`); return; }
  const invite=data.invite, company=data.company, employee=data.employee;
  const logged=!!session;
  h(`<div class="login"><div class="card" style="max-width:920px"><div class="brand">SmartCore Technology</div><h1>${invite.invite_type==='owner'?'Company setup':'Employee onboarding'}</h1><p>${esc(company?.company_name||'')}</p>${!logged?`<div class="card"><h3>Create or sign into your account</h3><div class="form-grid"><label>Email<input id="on_email" value="${esc(invite.email)}"></label><label>Password<input id="on_pass" type="password" placeholder="Only needed if this is a new account"></label></div><p class="muted">If you already have a SmartCore account, sign in with your existing password. You will not need another password for this company.</p><button class="btn primary" id="on_auth">Continue</button></div>`:''}<div class="card" style="margin-top:16px"><h3>${invite.invite_type==='owner'?'Company defaults':'Personal details'}</h3><div class="form-grid">${invite.invite_type==='owner'?ownerSetupFields(company):employeeSetupFields(employee)}</div><button class="btn primary" style="margin-top:14px" id="completeBtn" ${logged?'':'disabled'}>Complete onboarding</button></div></div></div>`);
  if(!logged){ document.getElementById('on_auth').onclick=async()=>{ const email=val('on_email'), password=val('on_pass'); let r=await sb.auth.signInWithPassword({email,password}); if(r.error){ r=await sb.auth.signUp({email,password}); if(r.error) return toast(r.error.message); toast('Account created. Check your email if confirmation is required, then sign in.'); } else { session=r.data.session; toast('Signed in.'); renderOnboarding(token); } }; }
  document.getElementById('completeBtn').onclick=async()=>{ try{ const payload=invite.invite_type==='owner'?readOwnerPayload():readEmployeePayload(); await api('complete-onboarding',{token,user_id:session.user.id,payload}); toast('Onboarding complete.'); history.replaceState(null,'',APP_BASE); await loadContext(); if(memberships.length) enterCompany(company.id); else boot(); }catch(e){ toast(e.message); } };
}
function ownerSetupFields(c){ return `<label>Company legal/trading name<input id="o_company" value="${esc(c.company_name)}"></label><label>Display name<input id="o_display" value="${esc(c.display_name||c.company_name)}"></label><label>Address line 1<input id="o_addr1"></label><label>City<input id="o_city"></label><label>Postcode<input id="o_post"></label><label>Main email<input id="o_email" value="${esc(c.owner_email)}"></label><label>Main phone<input id="o_phone" value="${esc(c.owner_phone)}"></label><label>Holiday year start month<input id="o_month" type="number" value="1"></label><label>Holiday year start day<input id="o_day" type="number" value="1"></label><label>Bank holiday region<select id="o_region"><option value="england-and-wales">England and Wales</option><option value="scotland">Scotland</option><option value="northern-ireland">Northern Ireland</option></select></label><label>Default annual leave allowance<input id="o_allow" type="number" step="0.5" value="28"></label><label><span><input id="o_bh" type="checkbox" checked> Bank holidays included in allowance</span></label><label>Your job title<input id="o_job" value="Owner"></label><label>Your start date<input id="o_start" type="date"></label><label><span><input id="o_noauth" type="checkbox" checked> No authoriser required for owner</span></label><label>Max employees<input readonly value="${esc(c.max_employees)}"></label>`; }
function employeeSetupFields(e){ return `<label>Title<input id="p_title"></label><label>Full name<input id="p_full" value="${esc(e?.full_name)}"></label><label>Pronouns optional<input id="p_pronouns"></label><label>Date of birth<input id="p_dob" type="date"></label><label>National Insurance number<input id="p_ni"></label><label>Address line 1<input id="p_addr1"></label><label>Address line 2<input id="p_addr2"></label><label>City<input id="p_city"></label><label>County<input id="p_county"></label><label>Postcode<input id="p_post"></label><label>Country<input id="p_country" value="United Kingdom"></label><label>Emergency contact 1 name<input id="p_ec1"></label><label>Emergency contact 1 relationship<input id="p_ecr1"></label><label>Emergency contact 1 email<input id="p_ece1"></label><label>Emergency contact 1 phone<input id="p_ecp1"></label><label>Emergency contact 2 name optional<input id="p_ec2"></label><label>Emergency contact 2 relationship optional<input id="p_ecr2"></label><label>Emergency contact 2 email optional<input id="p_ece2"></label><label>Emergency contact 2 phone optional<input id="p_ecp2"></label>`; }
function readOwnerPayload(){ return {company_name:val('o_company'),display_name:val('o_display'),address_line_1:val('o_addr1'),city:val('o_city'),postcode:val('o_post'),main_email:val('o_email'),main_phone:val('o_phone'),holiday_year_start_month:Number(val('o_month')),holiday_year_start_day:Number(val('o_day')),default_bank_holiday_region:val('o_region'),default_annual_leave_allowance:Number(val('o_allow')),bank_holidays_included_in_allowance:document.getElementById('o_bh').checked,owner_job_title:val('o_job'),owner_start_date:val('o_start')||null,no_authoriser_required:document.getElementById('o_noauth').checked}; }
function readEmployeePayload(){ return {title:val('p_title'),full_name:val('p_full'),pronouns:val('p_pronouns'),dob:val('p_dob')||null,national_insurance_number:val('p_ni'),address_line_1:val('p_addr1'),address_line_2:val('p_addr2'),city:val('p_city'),county:val('p_county'),postcode:val('p_post'),country:val('p_country'),emergency_contact_1_name:val('p_ec1'),emergency_contact_1_relationship:val('p_ecr1'),emergency_contact_1_email:val('p_ece1'),emergency_contact_1_phone:val('p_ecp1'),emergency_contact_2_name:val('p_ec2'),emergency_contact_2_relationship:val('p_ecr2'),emergency_contact_2_email:val('p_ece2'),emergency_contact_2_phone:val('p_ecp2')}; }
init();
