-- ============================================================================
-- SmartCore Flexi — Migration 6: Trainer-code + passcode client auth
--
-- Replaces Supabase-Auth-based client login (client-invite.html signUp flow)
-- with a custom, service-role-mediated session model: clients never get an
-- auth.users row. They log in with a company-wide trainer_code (so the app
-- knows which tenant to look in) plus their email and a 5-character passcode
-- generated by the trainer, hashed here, and emailed on creation. All portal
-- reads/writes now go through functions/api/flexi/portal-api.js using the
-- service-role key rather than through RLS + auth.uid() (which is always
-- NULL for these requests since there is no Supabase Auth session).
--
-- The old auth_user_id column, the smartcore_flexi_client_invites table and
-- the flexi_get_invite/flexi_accept_invite/flexi_current_client(_id) RPCs are
-- left in place but unused going forward — nothing references them from the
-- new flow, and removing them isn't necessary (this repo's migrations don't
-- drop objects; harmless to leave dead columns/tables behind).
-- ============================================================================

ALTER TABLE public.smartcore_flexi_settings
  ADD COLUMN IF NOT EXISTS trainer_code text UNIQUE;

ALTER TABLE public.smartcore_flexi_clients
  ADD COLUMN IF NOT EXISTS passcode_hash text,
  ADD COLUMN IF NOT EXISTS session_token text UNIQUE,
  ADD COLUMN IF NOT EXISTS session_expires_at timestamptz;

CREATE INDEX IF NOT EXISTS smartcore_flexi_clients_session_token_idx ON public.smartcore_flexi_clients(session_token);

-- ----------------------------------------------------------------------------
-- flexi_ensure_trainer_code — fetches the calling employee's company's
-- trainer code, generating one on first use (or regenerating with
-- p_force := true). Runs as the caller (not SECURITY DEFINER) so RLS on
-- smartcore_flexi_settings still gates it to company members; the code
-- itself carries no secrets (it's a routing key, not a credential), so any
-- employee — not just admins — can view/share it with new clients.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.flexi_ensure_trainer_code(p_company_id uuid, p_force boolean DEFAULT false)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_code text;
  v_charset text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; -- no 0/O/1/I/L
  v_is_member boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM public.core_employees ce WHERE ce.auth_user_id = auth.uid() AND ce.company_id = p_company_id
  ) INTO v_is_member;
  IF NOT v_is_member THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  SELECT trainer_code INTO v_code FROM public.smartcore_flexi_settings WHERE company_id = p_company_id;

  IF v_code IS NOT NULL AND NOT p_force THEN
    RETURN v_code;
  END IF;

  LOOP
    v_code := (
      SELECT string_agg(substr(v_charset, (floor(random() * length(v_charset)) + 1)::int, 1), '')
      FROM generate_series(1, 6)
    );
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.smartcore_flexi_settings WHERE trainer_code = v_code);
  END LOOP;

  INSERT INTO public.smartcore_flexi_settings (company_id, trainer_code, updated_at)
  VALUES (p_company_id, v_code, now())
  ON CONFLICT (company_id) DO UPDATE SET trainer_code = excluded.trainer_code, updated_at = now();

  RETURN v_code;
END;
$$;

REVOKE ALL ON FUNCTION public.flexi_ensure_trainer_code(uuid, boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.flexi_ensure_trainer_code(uuid, boolean) FROM anon;
GRANT EXECUTE ON FUNCTION public.flexi_ensure_trainer_code(uuid, boolean) TO authenticated;
